"""
OCBM v1 (GL trees) on MNIST -> ACC_Y.

Like ocbm-v1-mnist but the per-digit trees are the HIERARCHICAL, GRADED-LOGIC
trees generated by OCBM_V1_TREE_PROMPT.md (trees/mnist_v1.json): sub-scores per
domain (present-strokes soft-conjunction, absent-strokes hard-conjunction, ...),
GCD operators (HC/SC/HD), per-input weights, graded negation -- evaluated with
lsp_power_mean.  Fixed (v1) vs the plain AND/OR baseline (ocbm-v1-mnist).

    python ocbm-glv1-mnist-accuracy.py --iters 10
"""

from __future__ import annotations

import argparse
import json
import os

import _bench
import _gltree

TRAINABLE, COL, LABEL = False, "MNIST", "OCBM v1 (GL)"
_TREES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "trees", "mnist_v1.json")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--iters", type=int, default=5)
    ap.add_argument("--epochs", type=int, default=6)
    ap.add_argument("--batch-size", type=int, default=256)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--lam", type=float, default=1.0)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--trees", type=str, default=_TREES)
    args = ap.parse_args()

    device = _bench.get_device()
    spec = _bench.mnist_concept_spec(device)
    with open(args.trees, "r", encoding="utf-8") as f:
        trees = json.load(f)
    print(f"{LABEL} / {COL}   iters={args.iters}  epochs={args.epochs}  "
          f"trainable={TRAINABLE}  trees={os.path.basename(args.trees)}  device={device}")

    acc_y = []
    for it in range(args.iters):
        _bench.set_seed(args.seed + it)
        tl, vl = _bench.mnist_loaders(args.batch_size)
        model = _gltree.GLTreeCBM(spec.concept_names, trees, trainable=TRAINABLE)
        _bench.train_with_concepts(model, tl, spec.target_fn, device,
                                   epochs=args.epochs, lr=args.lr, lam=args.lam)
        a = _bench.task_accuracy(model, vl, device)
        acc_y.append(a)
        print(f"  [iter {it + 1}/{args.iters}]  ACC_Y = {a * 100:.2f}")

    _bench.report(LABEL, COL, acc_y)


if __name__ == "__main__":
    main()
